FROM python:3.11-slim

WORKDIR /app

ENV POETRY_VIRTUALENVS_CREATE=false \
    POETRY_NO_INTERACTION=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app/src

RUN pip install --no-cache-dir poetry debugpy

COPY requirements-lite.txt ./

RUN pip install --no-cache-dir -r requirements-lite.txt

COPY src ./src

EXPOSE 8000 5678

CMD ["uvicorn", "tweetpulse.main:app", "--host", "0.0.0.0"]
